### ISSUE TITLE
CastillejoLobatoJoseAntonioPrueba19Ma

### ISSUE THREAD

**Issue by casti-lob** [casti-lob/TrabajoProgramacion#18]
Examen corregido, he tenido que cambiar la extensión d los ficheros por txt porque a la hora de clonar el repositorio me daba fallo

**Comment by ioliasa** [comment]
Lo de la extensión no tiene ningún sentido, vuelve a ponerle csv y me dices que fallo te da.
El comparteTo de Temporada no lo veo, por qué pones 1 menos el resto, si quieres que vaya en orden contrario pone un paréntesis y un menos delante.

**Comment by casti-lob** [comment]
Arreglado lo del 1 se me había colado
